### ISSUE TITLE
Suggestions for more emojis

### ISSUE THREAD

**Issue by mkj-is** [xxdavid/emoji-term#1]
Hi!

I have some suggestions to make the list more complete (there are some Ruby and OS X specific items):

```
fax
fold
pod
look
head
tail
bless
find
toe
time
tidy
tie
python
puma
test
thin
swift
spring
spray
split
port
mount
mail
mag
locate
gunzip
groups
gem
fold
column
clear
chat
case
exit
kill
what
wish
weave
wait
unicorn
size
say
shift
open
```

What do you think?

**Comment by xxdavid** [comment]
Hi Matěj, **thank you** for the suggestions! :clap: 

I added some of your suggestions with 787f195.

However, I couldn't find emojis that would match these commands:
- pod
- tail
- bless
- tidy
- test
- thin
- spray
- split
- mag
- gunzip
- column
- case
- exit
- wish
- open

Would you mind finding appropriate emojis for them?

I also have two questions:
- What is `unicorn`?
- Do you mean Spring, the Java framework? If so, are you sure it has a CLI (I don't know, I've never used Spring)?

**Comment by mkj-is** [comment]
No problem. Happy I could help. Good point, I couldn't find any usable for these items either. The only idea I have is 🔫🤐 (two emojis) and 🦄 is a HTTP server. ♨️ is 🛤 application preloader. So, basically both of them are 💎 on 🛤 related.

**Comment by xxdavid** [comment]
Sorry I'm not a 💎/ 🛤 developer so I didn't know those libraries. :sob: But I have added them. 🎉

:gun: 🤐 would be more complicated so I won't do it now.

Thank you for your contribution. :clap: :smile:

**Comment by zvonicek** [comment]
I have a short follow-up to your discussion. I think these icons could be used as a representations of the not yet assigned commands _open_ and _bless_.
- 🔓– open
- 🙏🏽 or 🙌 – bless

**Comment by xxdavid** [comment]
Added. Thank you, Petr! 👍
